### ISSUE TITLE
how to generate non_aligned_concept_tagging/train* files

### ISSUE THREAD

**Issue by xiehou-design** [PKUnlp-icler/Two-Stage-CAMRP#4]
I have seen your code, but `preprocess.py` does not tell me how to generate it. Looking forward to your reply.

**Comment by chenllliang** [comment]
sorry for the delay， we'll update ASAP

**Comment by KbsdJames** [comment]
Thanks for raising the issue, we have updated the relevant code in `preprocess.py`.
